### ISSUE TITLE
Update to Blender 4.0

### ISSUE THREAD

**Issue by MajorCookie** [BlenderBoi/Vertex_Group_Utils#2]
Is there any chance to update the addon for version 4.0? It started giving an error when launching it

**Comment by BlenderBoi** [comment]
I will look into it

**Comment by MajorCookie** [comment]
> I will look into it
Thank you!

**Comment by BlenderBoi** [comment]
Hi, Unfortunately Blender 4.0 breaks alot of things in Vertex Group Utils, there is a chance that a rewrite is needed, which will not be very fast

do you have any specific feature you urgently needed right now from Vertex Group Utils?

**Comment by MajorCookie** [comment]
Hi. Yes, I use "Join Objects as Vertex Groups", "Separate Vertex Group into Objects", "Remove Empty Group", "Separate All" very often. The rest, not so often. Mostly I need to quickly create groups from objects, because manually I take a lot of time when there are more than 100 objects

**Comment by BlenderBoi** [comment]
Unfortunately this will take some time to fix as I have other priorities

Is it possible to use the older version of blender as for now?

**Comment by MajorCookie** [comment]
To use, yes, you can. But for now I can use the standard blender functionality for vertex group. I really like using this addon, so the wait is worth 15 dollars :)

**Comment by BlenderBoi** [comment]
I added a Hotfix to get it at least work on Blender 4.0, use the hotfix4.0 branch for that
It is not heavily tested though

I will do a more proper update release in future as Im quite occupied

**Comment by BlenderBoi** [comment]
The feature you listed should work fine in the hotfix

**Comment by MajorCookie** [comment]
Perfect. Worked well right now. Will wait for the main release. Thank you. I'll close the issue
